# Site settings
title: "Altcoin Wisdom"
subtitle: ""
description: "Altcoin Trading charts with technical analysis indicators."
baseurl: ""
url: "https://altcoinwisdom.com"
#url: "http://127.0.0.1:4000"
author: "Altcoin Trader"
# Build settings
markdown: kramdown
## Default image size: 700x360
ads:
  ledger: '<div class="text-center"><a rel="nofollow" target="_blank" href="https://www.ledgerwallet.com/r/e274"><img alt="Ledger Wallet protects your bitcoins" src="https://www.ledgerwallet.com/images/promo/ledger-468x90-01.jpg"></a></div>'
